// <auto-generated />
using FakeBet.Models;
using FakeBet.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FakeBet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180221181504_upd")]
    partial class upd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FakeBet.Models.Match", b =>
                {
                    b.Property<string>("MatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<DateTime>("MatchTime");

                    b.Property<float>("PointsRatio");

                    b.Property<int>("Status");

                    b.Property<string>("TeamAName");

                    b.Property<int>("TeamAPoints");

                    b.Property<string>("TeamBName");

                    b.Property<int>("TeamBPoints");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FakeBet.Models.User", b =>
                {
                    b.Property<string>("NickName")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("Points");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("Status");

                    b.HasKey("NickName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FakeBet.Models.Vote", b =>
                {
                    b.Property<Guid>("VoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("MatchId");

                    b.Property<string>("MatchId1");

                    b.Property<Guid>("UserId");

                    b.Property<string>("UserNickName");

                    b.Property<int>("UserPick");

                    b.Property<int>("UserPoints");

                    b.HasKey("VoteId");

                    b.HasIndex("MatchId1");

                    b.HasIndex("UserNickName");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("FakeBet.Models.Vote", b =>
                {
                    b.HasOne("FakeBet.Models.Match", "Match")
                        .WithMany("Votes")
                        .HasForeignKey("MatchId1");

                    b.HasOne("FakeBet.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserNickName");
                });
#pragma warning restore 612, 618
        }
    }
}
